steps:
- name: python:3.7
  args: ['pip', 'install', '-r', 'requirements.txt']
  id: build
- name: python:3.7
  args: ["python","-m","unittest","discover"]
  id: testing
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  id: deploy
timeout: "1600s"