steps:
- name: python:3.7
  entrypoint: python3
  args: ["-m", "pip", "install", "-t", ".", "-r", "requirements.txt"]
  id: install
- name: python:3.7
  entrypoint: python3
  args: ["manage.py", "test"]
  env:
    - "DJANGO_SETTINGS_MODULE=portal.settings"
  id: testing
  waitFor:
    - install
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  id: deploy
  waitFor:
    - testing
timeout: "1600s"